services:
  moscow-time-app:
    build:
      context: ./app_python
    image: moscow-time-app:1.0.0
    container_name: moscow-time-app
    ports:
      - "8080:8080"
    environment:
      VISITS_FILE: /home/appuser/visits
    volumes:
      - ./app_python/visits:/home/appuser/visits
