apiVersion: v1
kind: Service
metadata:
  name: moscow-time-app
  labels:
    app: moscow-time-app
spec:
  type: NodePort
  selector:
    app: moscow-time-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: moscow-time-app-headless
  labels:
    app: moscow-time-app
spec:
  clusterIP: None
  selector:
    app: moscow-time-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
