{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moscow-time-app.secretName" . }}
  labels:
    {{- include "moscow-time-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secret.passwordKey }}: {{ .Values.secret.password | quote }}
{{- end }}
